ROOT_DIR= "/Users/ilian/Desktop/research_projects/c3ai-covidchallenge/covid_activity/"
DATASET_DIR= "/Users/ilian/Desktop/research_projects/c3ai-covidchallenge/covid_activity/data"
cols = [
       'Accommodation',
       'Accommodation and Food Services',
       'Administrative and Support Services',
       'Administrative and Support and Waste Management and Remediation Services',
       'Agriculture, Forestry, Fishing and Hunting',
       'Ambulatory Health Care Services',
       'Amusement, Gambling, and Recreation Industries',
       'Arts, Entertainment, and Recreation',
       'Automotive Repair and Maintenance',
       'Building Material and Garden Equipment and Supplies Dealers',
       'Clothing and Clothing Accessories Stores',
       'Commercial and Industrial Machinery and Equipment (except Automotive and Electronic) Repair and Maintenance',
       'Construction', 'Construction of Buildings',
       'Credit Intermediation and Related Activities',
       'Death Care Services', 'Drycleaning and Laundry Services',
       'Educational Services', 'Fabricated Metal Product Manufacturing',
       'Finance and Insurance', 'Fishing, Hunting and Trapping',
       'Food Manufacturing', 'Food Services and Drinking Places',
       'Food and Beverage Stores', 'Forestry and Logging',
       'Furniture and Home Furnishings Stores',
       'Furniture and Related Product Manufacturing', 'Gasoline Stations',
       'General Merchandise Stores', 'Health Care and Social Assistance',
       'Health and Personal Care Stores',
       'Heavy and Civil Engineering Construction',
       'Independent Artists, Writers, and Performers',
       'Industries not classified', 'Information',
       'Insurance Carriers and Related Activities',
       'Machinery Manufacturing',
       'Management of Companies and Enterprises', 'Manufacturing',
       'Merchant Wholesalers, Durable Goods',
       'Merchant Wholesalers, Nondurable Goods',
       'Mining, Quarrying, and Oil and Gas Extraction',
       'Miscellaneous Manufacturing', 'Miscellaneous Store Retailers',
       'Motor Vehicle and Parts Dealers',
       'Nonmetallic Mineral Product Manufacturing', 'Nonstore Retailers',
       'Nursing and Residential Care Facilities',
       'Other Information Services', 'Other Personal Services',
       'Other Services (except Public Administration)',
       'Performing Arts Companies',
       'Performing Arts, Spectator Sports, and Related Industries',
       'Personal Care Services',
       'Personal and Household Goods Repair and Maintenance',
       'Personal and Laundry Services',
       'Plastics and Rubber Products Manufacturing',
       'Primary Metal Manufacturing',
       'Printing and Related Support Activities',
       'Professional, Scientific, and Technical Services',
       'Publishing Industries (except Internet)', 'Real Estate',
       'Real Estate and Rental and Leasing', 'Religious Organizations',
       'Religious, Grantmaking, Civic, Professional, and Similar Organizations',
       'Rental and Leasing Services', 'Repair and Maintenance',
       'Restaurants and Other Eating Places', 'Retail Trade',
       'Securities, Commodity Contracts, and Other Financial Investments and Related Activities',
       'Social Assistance', 'Special Food Services',
       'Specialty Trade Contractors', 'Spectator Sports',
       'Sporting Goods, Hobby, Musical Instrument, and Book Stores',
       'Support Activities for Agriculture and Forestry',
       'Support Activities for Transportation', 'Telecommunications',
       'Transit and Ground Passenger Transportation',
       'Transportation and Warehousing', 'Traveler Accommodation',
       'Truck Transportation', 'Utilities',
       'Wholesale Electronic Markets and Agents and Brokers',
       'Wholesale Trade', 'Wood Product Manufacturing', 'population_density',
        ]
